# Page settings
baseurl = "https://dashing-panda-01b2f7.netlify.app/"
title = "PGDPIE"
languageCode = "en-us"
theme = "pgdpie_theme"


[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  googleFonts = "https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"

  # Meta
  author = "PGDIPE Coordination"
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "images/logoEN.svg"
    home = "Home"
    services = "About"
    work = "Projects 2022-23"
    about = "Team"
    testimonials = "Testimonials"
    contact = "Contact"
    PT = "PT"
  

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://fabschools.pt/"
      name = "PT"
      weight = 10
  
  # Hero section
  [params.hero]
    title = "The postgraduate course in Design of Interactive Products for Education"
    subtitle = 'equips design and education professionals with the necessary skills for seamless integration within multidisciplinary teams, focusing on the design, selection, and implementation of interactive products for education across various domains including toys, open educational resources, interactive graphics, and Fablab prototyping.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Hey! Designer?"
    description = "Elevate your expertise in interactive product design for education and seamlessly integrate with multidisciplinary teams through our postgraduate course."
    # url = "#about"
    # button = "Know More"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Teacher? Educator?"
    description = "Unlock new possibilities in educational design by honing your skills in selecting and implementing interactive products for education through our specialized postgraduate program."
    # url = "#about"
    # button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = " other Education or Design Professionals?"
    description = "Expand your horizons and boost your career by acquiring advanced skills in designing, selecting, and implementing interactive products for education."
    # url = "#about"
    # button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  
    

  # Services section
  [params.services]
    enable = true
    title = "About the Course"
    description = "Our course embraces an expansive and inclusive view of interactive products, encompassing a wide range of mediums, from apps to toys, and from digital to tangible experiences. The curriculum places emphasis on a final project, evaluated through the CU of Interactive Product Design for Education, which is integrated from the course's inception. Throughout the program, this project is formulated, developed, and guided across various Curricular Units, addressing relevant themes and tools. Notably, Fablab Benfica, as an indispensable prototyping space, will serve as a vital resource throughout the course."
    subtitle = "Course structure"
    description2 = "The Postgraduate Course in Design of Interactive Products for Education has a total of 60 ECTS and a duration of 2 semesters, which aims at the deepening of skills in design and prototyping for the educational area, serving professionals both in the field of education and design wishing to develop products or projects within their institution or even embrace new opportunities in the area of interactive products for education."
  
    subtitle3 = "Objectives"
    description3 = ""
    subtitle4 = "Course structure"
    description4 = "The Postgraduate Course in Design of Interactive Products for Education has a total of 60 ECTS and a duration of 2 semesters, which aims at the deepening of skills in design and prototyping for the educational area, serving professionals both in the field of education and design wishing to develop products or projects within their institution or even embrace new opportunities in the area of interactive products for education."



    [[params.services.item]]
      title = "Objectives"
      description = ""
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Educations &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Team"
    description = "Meet our team of Professors"

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "PGDIPE in Numbers"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Horas de Contacto"
      icon = "icon-clock"
      from = 0
      to = 360
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "ECTS"
      icon = "icon-briefcase"
      from = 0
      to = 60
      interval = 5
      speed = 3000

      [[params.counters.item]]
      description = "Final Project Hours"
      icon = "icon-pencil"
      from = 0
      to = 120
      interval = 10
      speed = 4000

      [[params.counters.item]]
      description = "Projects"
      icon = "icon-paper"
      from = 0
      to = 1
      interval = 1
      speed = 500

# Work section
  [params.work]
    enable = true
    title = "Final Projects 2022-23"
    description = "Our first edition sign of success is inscribed in the quality of the final projects and the enthusiasm expressed by the students in their final presentations. All went directly to our fabschools catalog so we can keep track of future developments and documentation."
    footertext = 'The projects will link to their fabschools.pt catalog entries'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Animalgama"
      title = "Animalgama"
      subtitle = "Building blocks for learning about animals"
      url = "https://sites.google.com/view/animalgama"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "UP"
      title = "UP - Unidades Precisas"
      subtitle = "A classroom game about units"
      url = "https://sites.google.com/view/unidades-precisas/"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "GameleonEDU"
      title = "GameleonEDU"
      subtitle = "A platform that builds games for any content"
      url = "https://gameleonedu.github.io/gameleon.edu/index.html"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Print out of the Box"
      title = "Print out of the Box"
      subtitle = "Printmaking pedagogical kit"
      url = "https://m.facebook.com/artetransformer"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Adrinkadeira"
      title = "Adrinkadeira"
      subtitle = "A game to create stories, poems, and writings"
      url = "https://sites.google.com/view/adinkradeira"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Chão de Imaginação"
      subtitle = "Origami tapestry for children"
      url = ""

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Campus de Benfica do IPL, 1549-003 Lisboa"],
        ["icon-phone", "+351 217 100 000"],
        ["icon-envelope", ""],
        ["icon-globe", '<a href="http://fabschools.pt" target="_blank">PGDIPE is part of fabschools@ESELx/IPL</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'cc-by PGDPIE coordination team at ESELx-IPL'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
